### ISSUE TITLE
LICENSE Error on Install

### ISSUE THREAD

**Issue by PaperDoom** [caerulex/doc-proofreader#3]
In the pyproject.toml files:

```
license = "MIT"
```

This line creates an install error. Not sure if it's just my particular environment on MacOS, but I changed it to :

```
license = { file = "LICENSE" }
```

This fixed the problem for me and also points to your actual license file.

I didn't want to create a pull request for this because I didn't go test it on linux or windows.

**Comment by caerulex** [comment]
Resolved by MR #6
